version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - ashwanthkumar
  assignees:
  - ashwanthkumar
  ignore:
  - dependency-name: com.google.http-client:google-http-client-gson
    versions:
    - 1.38.1
    - 1.39.1
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
